# Generated by Django 2.1 on 2019-12-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.FileField(blank=True, default='album_logos/no-image.jpg', upload_to='images/'),
        ),
    ]
